### ISSUE TITLE
example/raspberrypi/relay /main.py - no state change

### ISSUE THREAD

**Issue by toms77** [Wappsto/python-wappsto-iot#6]
Hi

I have tried the example file as is
https://github.com/Wappsto/python-wappsto-iot/blob/main/example/raspberrypi/relay/main.py.

It do not, return any errors, but it do not change the state of the relay on/off. It do not change on the dashboard either.

The pin number is corret.

What am I missing in this file?

**Comment by tacozMacleo** [comment]
Hey @toms77.
It could be many things, so we can start with the basic.
1) Have you make sure that there are a `ca.crt`, client`.key` and a `client.crt´ in your config folder?
2) Are your `relay_control` function triggered when you toggle the switch on wappsto?
     1)  If the `relay_control` function is triggered, it will be something to do with the GPIO library/setup.
     2) IF the `relay_control` function is _not_ triggered, it is the WappstoIoT library/config, and we will need a log output. (Use the default [python logging module](https://docs.python.org/3/library/logging.html#logging.basicConfig). Can be a bit spamy, so using the [RichHandler](https://rich.readthedocs.io/en/stable/logging.html). Examples shown below.)

  
  ```python
import logging
from rich.logging import RichHandler

# With Rich Handler.
logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s - %(name)s - %(message)s",
    handlers=[RichHandler()],
)
# Without Rich Handler.
logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s - %(name)s - %(message)s",
)
```

When you have setup the logging, started up the script and letting it connect & setup all the values, (the Spamy part). When it have settled, toggle the switch on Wappsto and see if there is received some data.

**(Before you post any log output, please remove your Devices IP (found in the start of the file), and replace all uuids with '\*\*\*', can be done with: `sed -E 's/([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12})/***/'`)

**Comment by toms77** [comment]
Hey @tacozMacleo 

Thanks, for the help with the logging, that went smooth. 👍 

The problem seems to fall under part 2) I'm getting a value error.

`ERROR    2024-01-03 11:12:17,723 - wappstoiot.modules.value -     value.py:563
                             OnChange callback error.
                             Traceback (most recent call last):
                               File
                             "/home/toms/.local/lib/python3.9/site-packages/wappstoio
                             t/modules/value.py", line 561, in _cb_float
                                 callback(self, data)
                               File "/home/toms/FlowerPower/main.py", line 211, in
                             relay_control
                                 GPIO.output(water_pump_pin, new_value)
                             ValueError: Value must be an integer/boolean or a
                             list/tuple of integers/booleans`

The template settings: (as the example)
```
permission=wappstoiot.PermissionType.READWRITE,
        value_template=wappstoiot.ValueTemplate.BOOLEAN_ONOFF
```
The pin name is just changed:
`water_pump_pin = 5`

Any sugestings to why it rapports a ValueError??

**Comment by tacozMacleo** [comment]
Aaarh.
The RPi.GPIO says that it need a integer or a boolean. The new_value are a float or a string. So it need to be converted to a int. So replace: `GPIO.output(relay_pin, new_value)` with: `GPIO.output(relay_pin, int(new_value))` and it should work.
 
Do you mind add: `print(type(new_value)` in the `relay_control` and give me that print line, to see if it is WappstoIoT that give you wrong type, or it is `RPi.GPIO` that is pedantic about integer or float?
Thanks.

**Comment by toms77** [comment]
Sure thing

new_value  = <class 'float'>

This must come from the mapping in valuetemplate?

**Comment by tacozMacleo** [comment]
Thanks, It seems that it is RPi.GPIO that is more pedantic about it. I will fix the example code. And make it as resolved.

Yes, the `Wappsto.ValueTemplate.BOOLEAN_ONOFF` given the config for a number value, so that is set up behind the screens.
`Wappsto.ValueTemplate` have a long list of default templates. If none of them fits your needs, you can always setup your own with: `device.createStringValue` or `device.createNumberValue`.
If your IntelliSense do not show you them, you can find a list in: [wappsto/iot/modules/template.py](https://github.com/Wappsto/python-wappsto-iot/blob/main/wappstoiot/modules/template.py#L47C15-L47C15)

**Comment by toms77** [comment]
Thanks, I have acutely been looking for an example off how to create your own valuetemplate and been looking at the template fil  a lot. It would have been nice with the "make you own template" recipe in the comments of that template file. 

Thanks for the help.
